//loaders
export const WORLD_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const WORLD_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// World general case
export const WORLD_GENERAL_REQUEST = 'WORLD_GENERAL_REQUEST';
export const WORLD_GENERAL_RESPONSE = 'WORLD_GENERAL_RESPONSE';
export const WORLD_GENERAL_FAILED = 'WORLD_GENERAL_FAILED';

export const COUNTRIES_REQUEST = 'COUNTRIES_REQUEST';
export const COUNTRIES_RESPONSE = 'COUNTRIES_RESPONSE';
export const COUNTRIES_FAILED = 'COUNTRIES_FAILED';