
module.exports = {
    totalCase: "Total Cases: ",
    recoveryCase: "Recovery cases: ",
    deathCases: "Death cases: ",
    currentlyInfected: "Currently infected: ",
    casesOutcome: "Cases with outcome: ",
    mildCases: "Mild condition active cases: ",
    criticalCondition: "Critical condition active cases: ",
    recoveredclosed: "Recovered closed cases: ",
    deathclosed: "Death closed cases: ",
    closedRecovered: "Closed cases recovered percentage: ",
    closedDeath: "Closed cases death percentage: ",
    activeMild: "Active cases mild percentage: ",
    activeCritical: "Active cases critical percentage: ",
    generalDeath: "General death rate: ",
    country: "Country: ",
    newCases: "New cases: ",
    totalDeaths: "Total deaths: ",
    newDeaths: "New deaths: ",
    totalRecovered: "Total recovered: ",
    activeCases: "Active cases: ",
    seriousCritical: "Serious critical: ",
    casesMill: "Cases per mill pop: ",
};
